### ISSUE TITLE
Roadmap Needed

### ISSUE THREAD

**Issue by captn3m0** [rk/uFramework#4]
I'm willing to work on uFramework, but I'm not very sure where you'd want to go with this. I was thinking of giving some good plug-gable support for external libraries. (esp [Redbean](http://redbeanphp.com)). 

This would make uF much more easier to work with. Of course this brings along the additional baggage of models, but ORM/DB support would be very nice to work with. 
And I'd like to keep it optional. Just change a config, and you're ready with a full-fledged orm support.

**Comment by rk** [comment]
uFramework does need some attention. It has sat here and not advanced for quite a while (but then, I haven't done any independent PHP work in a while).

I'm willing to collaborate with you in adding plugin support to uFramework. I also want to tidy the framework up; a break of a year and a half have sure given me new eyes when looking at my code. I haven't had much feedback on what is (dis-)liked or what needs work.

So for a basic roadmap, I think version 1.0 needs:
- Plug-in support.
- Some clean up and better commenting
- Improved / updated documentation
- A better `view()` method; no more stumbling about for filenames but do a GLOB to find if anything matches the name and take the first.

I may think of more things later. Your thoughts?

**Comment by captn3m0** [comment]
Amongst other things, we can also try for :
- models support (its more like View-Controller as it is)
- Basic application tutorial

**Comment by rk** [comment]
Well, Model support would be very rudimentary. The problem is, I've tried to make the system compatible with an ORM system if the developer wanted it. I don't know how I'd go about making a model system that is both simple, and compatible with work someone else might do.

A basic application tutorial would be easy enough to do.

**Comment by captn3m0** [comment]
I was thinking in the direction of redbeanphp, but you're correct. The system is useful with any ORM system as of now.

**Comment by rk** [comment]
Exactly.

If I was to build in a Model system it'd be easily turned off, because I want someone to have their choice of ORM. Now, is that a wise decision? Should I be opinionated in software design? I know this isn't Rails... but I haven't tried a PHP ORM solution; I have only hand-coded my SQL queries and data structures in PHP applications.

Maybe a model solution should be considered for 1.1 or 1.2. I think that it's most important to finalize the base framework and get it stable and secure prior to releasing 1.0.

**Comment by captn3m0** [comment]
What about plugin support which you mentioned earlier ? Could you elaborate a bit on that.

**Comment by rk** [comment]
I was thinking about the plugin system being something easily included, unlike how the includes directory is handled. This isn't final, but I was thinking of a directory structure like:

```
application/
    plugin/
        pChart/
            plugin.php
            ...
```

Basically, inside `pChart/plugin.php` is just the correct includes for the "plugin". So that additional things like RedBean can be packaged with a plugin.php file that loads the correct files; uFramework would just load `application/plugin/*/plugin.php` when initializing.

No guarantee in what order they'll be loaded in, though.
